#  Template maven-build

#  This template allows you to test and build your Java project with Maven.
#  The workflow allows running tests, code checkstyle and security scans on the default branch.

# Prerequisites: pom.xml and appropriate project structure should exist in the repository.

image: maven:3.6.3-jdk-11

options:
  max-time: 5

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file MesProjets/pom.xml
          after-script:
              # Collect checkstyle results, if any, and convert to Bitbucket Code Insights.
            - pipe: atlassian/checkstyle-report:0.2.0
      - step:
          name: Security Scan
          script:
            # Run a security scan for sensitive data.
            # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
            - pipe: atlassian/git-secrets-scan:0.4.3
    - step:
        name: Build and start Wildfly
        script:
          - mvn --file MesProjets/pom.xml clean install
          - mvn --file MesProjets/Tests/TestWeb/pom.xml wildfly:start
          - mvn --file MesProjets/Tests/TestWeb/pom.xml wildfly:deploy
          - sleep 1m
          - mvn --file MesProjets/Tests/TestWeb/pom.xml wildfly:shutdown
